model:
  base_model: "artemis-legal-base"
  model_path: "models/legal/base"
  
hybrid_adapter:
  enabled: true
  lora_rank: 8
  adapter_size: 64
  target_modules: 
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  apply_lora_to: 
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
  shared_parameters: false
  scaling_factor: 0.5

pruning:
  enabled: true
  method: "structured_pruning"
  sparsity: 0.55
  schedule: "cubic"
  start_step: 1000
  end_step: 10000
  
efficiency_transformer:
  enabled: true
  attention_method: "flash_attention"
  kv_cache_method: "quantized"
  memory_efficient: true
  
optimization:
  quantization: "int8"
  batch_processing: true
  distributed_inference: true
  max_sequence_length: 8192
  
legal_extensions:
  jurisdiction: "us"  # Options: us, uk, eu, canada, australia, international
  document_types: 
    - "contract"
    - "legislation"
    - "court_document"
    - "regulatory_filing"
  enable_case_law: true
  enable_citation_linking: true
  enable_risk_assessment: true
  precedent_database: "legal_precedents_2023"
  statute_database: "statutes_2023"
  
document_processing:
  ocr_engine: "tesseract"  # Options: tesseract, azure, google
  ocr_config:
    language: "eng"
    page_segmentation_mode: 1
    oem: 3
  layout_analysis: true
  table_extraction: true
  signatures_detection: true
  
extraction:
  clause_types:
    - "indemnification"
    - "limitation_of_liability"
    - "governing_law"
    - "dispute_resolution"
    - "termination"
    - "force_majeure"
    - "confidentiality"
    - "representations_warranties"
    - "assignment"
    - "amendment"
  entity_types:
    - "organization"
    - "person"
    - "location"
    - "date"
    - "monetary_value"
    - "duration"
    - "obligation"
    - "right"
    - "citation"
  extraction_method: "hybrid"  # Options: rule_based, ml, hybrid
  confidence_threshold: 0.75
  
analysis:
  risk_assessment_levels:
    - "high"
    - "medium"
    - "low"
    - "informational"
  semantic_similarity_threshold: 0.85
  cross_reference_enabled: true
  inconsistency_detection: true
  ambiguity_detection: true
  
summarization:
  max_summary_length: 1000
  include_key_clauses: true
  include_parties: true
  include_dates: true
  include_monetary_values: true
  include_issues: true
  
inference:
  max_tokens: 2048
  temperature: 0.1
  top_p: 0.92
  top_k: 50
  repetition_penalty: 1.05
  batch_size: 4
  
api_server:
  host: "0.0.0.0"
  port: 8000
  max_upload_size_mb: 50
  allowed_file_types:
    - "pdf"
    - "docx"
    - "txt"
    - "rtf"
    - "doc"
  cors_enabled: true
  allowed_origins:
    - "*"  # Adjust for production
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
  authentication:
    enabled: false  # Set to true for production
    method: "api_key"
  
data:
  training_data: "data/legal/train.jsonl"
  validation_data: "data/legal/val.jsonl"
  test_data: "data/legal/test.jsonl"
  
training:
  epochs: 3
  batch_size: 8
  learning_rate: 1e-5
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 8
  fp16: true
  evaluation_strategy: "steps"
  eval_steps: 500
  save_steps: 1000
  logging_steps: 100
  
evaluation:
  metrics:
    - "precision"
    - "recall"
    - "f1"
    - "accuracy"
    - "legal_accuracy"
  document_types:
    - "contracts"
    - "briefs"
    - "opinions"
    - "statutes"
    - "regulations"
